---
  # Title: app-savapage
  #
  # Author: Luc Rutten
  # File: tasks/cups-printers.yml
  #
  # Description:
  #   Adding printers via commandline via cups.

  - name: "Create ppd repository"
    file:
      path: /usr/share/ppd/savapage/
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: "Download PPD files to /usr/share/ppd/savapage/"
    get_url:
      url:  "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items: "{{ sava_cups_ppd }}"

  - name: "Configure printer via CLI (RAW)"
    raw: lpadmin -p "{{ item.name }}" -v "socket://{{ item.ipaddress }}:9100" -m "{{ item.model }}" -P "{{ item.ppd }}" -L "{{ item.location }}" -E
    with_items:  "{{ sava_cups_printers }}" 
