---
  # Title: app-pagasave
  #
  # Author: Luc Rutten
  # File: tasks/postgresql.yml
  #
  # Description:
  #   Open print portal postgresql configuration.

  - name: "Check version of postgresql in /etc/postgresql"
    shell: "ls /etc/postgresql/" 
    register: pgdb_version

  - name: "Display version of postgresql in /etc/postgresql"
    debug:
      var: pgdb_version.stdout

#  - name: "Transfer template //pg_hba.conf"  
#    template:
#      src: postgresql/pg_hba.conf.j2
#      dest: "/etc/postgresql/{{ pgdb_version.stdout }}/main/pg_hba.conf"
#      owner: postgres
#      group: postgres
#      mode: 0644
#      backup: yes
#    notify:
#      - restart_postgresql

  - name: "Transfer template postgresql/postgresql.sh.j2 to /tmp/postgresql.sh"
    template:
      src: postgresql/postgresql.sh.j2
      dest: "/tmp/postgresql.sh"
      owner: root
      group: root
      mode: 0755

  - name: "Execute /tmp/postgresql.sh to create {{ sava_pgdb_dbuser }} and {{ sava_pgdb_dbname }}"
    command: /tmp/postgresql.sh

  - name: "Cleanup /tmp/postgresql.sh"
    file:
      path: "/tmp/postgresql.sh"
      state: absent
